version: 0.1.{build}
os: Visual Studio 2015
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
artifacts:
- path: MarketInvoice.CodeAnalysis.Vsix\bin\$(configuration)\MarketInvoice.CodeAnalysis.vsix